#第一个配置文件
SERVER:
  PORT: 8081
SPRING:
  PROFILES:
    ACTIVE: PRODUCT #激活哪个配置文件
---
#第二个配置文件
SERVER:
  PORT: 8082
SPRING:
  PROFILES: DEV
---
#第三个配置文件
SERVER:
  PORT: 8080
  #  增加链接,thymeleaf会自动加上
  servlet:
    context-path: /crud
SPRING:
  PROFILES: PRODUCT
  messages:
    basename: i18n.login
   #properties 前缀名

#PERSON:
#  NAME: ZHANGSAN
#  AGE: 18
#  BOSS: FALSE
#  BIRTH: 2018/1/1
#  MAP:
#    K1: 1
#    K2: 116
#  DOG:
#    NAME: 二哈
#    AGE: 2
#  LIST:
#    - 华为
#    - 小米

