#第一个配置文件
SERVER:
  PORT: 8081
SPRING:
  PROFILES:
    ACTIVE: PRODUCT #激活哪个配置文件
---
#第二个配置文件
SERVER:
  PORT: 8082
SPRING:
  PROFILES: DEV
---
#第三个配置文件
SERVER:
  PORT: 8080
#  #  增加链接,thymeleaf会自动加上
#  servlet:
#    context-path: /crud
SPRING:
  PROFILES: PRODUCT
  messages:
    basename: i18n.login
  mvc:
    date-format: yyyy-MM-dd HH:mm
   #properties 前缀名
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: '123456'
    port: 6379

#PERSON:
#  NAME: ZHANGSAN
#  AGE: 18
#  BOSS: FALSE
#  BIRTH: 2018/1/1
#  MAP:
#    K1: 1
#    K2: 116
#  DOG:
#    NAME: 二哈
#    AGE: 2
#  LIST:
#    - 华为
#    - 小米


#redis配置

